json.id order_detail.id
json.link order_detail.link
json.amount order_detail.amount
json.api_order_id order_detail.api_order_id
json.status order_detail.status
json.error_message order_detail.order_fails.try(:last).try(:message)
json.order_row_id order_detail.order_row_id
json.created_at order_detail.created_at.to_i
json.updated_at order_detail.updated_at.to_i